apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spin
    app.kubernetes.io/name: {{ .Release.Name | lower }}
    app.kubernetes.io/part-of: spinnaker
    cluster: {{ include "remote-agent.fullname" . }}
  name: {{ include "remote-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: {{ include "remote-agent.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spin
        app.kubernetes.io/name: armory-agent
        app.kubernetes.io/part-of: spinnaker
        cluster: {{ include "remote-agent.fullname" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: health
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: armory-agent
        ports:
        - containerPort: 8082
          name: health
          protocol: TCP
        - containerPort: 8008
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/armory/config
          name: volume-armory-agent-config
        - mountPath: /kubeconfigfiles
          name: volume-armory-agent-kubeconfigs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-armory-agent-config
        configMap:
          name: {{ .Release.Name | lower }}-config
      - name: volume-armory-agent-kubeconfigs
        secret:
          defaultMode: 420
          secretName: spin-secrets-remote