# Default values for remote-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

config:
  clouddriver:
    grpc: spin-clouddriver-grpc.christine-zhao:9091
  kubernetes:
    accounts:
      name: remote-cluster
      #kubeconfigFile: /kubeconfigfiles/kubecfg-remote
      #kubeconfigFile: encryptedFile:secrets-manager!r:us-east-2!s:christine-spin-secrets-remote
      kubeconfigFile: encryptedFile:s3!r:us-east-2!b:christine-zhao-s3!f:secret/christine-spin-secrets-remote

image:
  repository: armory/agent-k8s
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.39"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
